<?php

/**
 * @copyright Copyright (C) eZ Systems AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

namespace EzSystems\EzPlatformAdminUi\Translation\Extractor;

use EzSystems\EzPlatformAdminUi\Translation\CustomExtractorInterface;
use JMS\TranslationBundle\Model\Message;
use JMS\TranslationBundle\Model\MessageCatalogue;
use JMS\TranslationBundle\Model\Message\XliffMessage;

/**
 * Generates translation strings for limitation types.
 */
class PolicyTranslationExtractor implements CustomExtractorInterface
{
    const MESSAGE_DOMAIN = 'forms';
    const MESSAGE_ID_PREFIX = 'role.policy.';
    const ALL_MODULES = 'all_modules';
    const ALL_FUNCTIONS = 'all_functions';
    const ALL_MODULES_ALL_FUNCTIONS = 'all_modules_all_functions';

    /** @var array */
    private $policyMap;

    /**
     * @param array $policyMap
     */
    public function __construct(array $policyMap)
    {
        $this->policyMap = $policyMap;
    }

    public function extract(MessageCatalogue $currentCatalogue = null): MessageCatalogue
    {
        $catalogue = new MessageCatalogue();

        $this->add($this->createMessage(self::ALL_MODULES, 'All modules'), $catalogue, $currentCatalogue);
        $this->add($this->createMessage(self::ALL_MODULES_ALL_FUNCTIONS, 'All modules / All functions'), $catalogue, $currentCatalogue);

        foreach ($this->policyMap as $module => $functionList) {
            $this->add($this->createMessage($module, $this->humanize($module)), $catalogue, $currentCatalogue);
            $this->add($this->createMessage($module . '.' . self::ALL_FUNCTIONS, $this->humanize($module) . ' / All functions'), $catalogue, $currentCatalogue);

            foreach ($functionList as $function => $limitationList) {
                $this->add($this->createMessage($module . '.' . $function, $this->humanize($module) . ' / ' . $this->humanize($function)), $catalogue, $currentCatalogue);
            }
        }

        return $catalogue;
    }

    /**
     * @param string $id
     * @param string $desc
     *
     * @return \JMS\TranslationBundle\Model\Message\XliffMessage|null
     */
    private function createMessage(string $id, string $desc): ?XliffMessage
    {
        $id = self::MESSAGE_ID_PREFIX . $id;

        $message = new XliffMessage($id, self::MESSAGE_DOMAIN);
        $message->setNew(false);
        $message->setMeaning($desc);
        $message->setDesc($desc);
        $message->setLocaleString($desc);
        $message->addNote(sprintf('key: %d (generated by %s)', $id, self::class));

        return $message;
    }

    /**
     * Makes a technical name human readable.
     *
     * Sequences of underscores are replaced by single spaces. The first letter
     * of the resulting string is capitalized, while all other letters are
     * turned to lowercase.
     *
     * @see \Symfony\Component\Form\FormRenderer::humanize()
     *
     * @param string $text the text to humanize
     *
     * @return string the humanized text
     */
    private function humanize(string $text): string
    {
        $replace = ['Content Type'];
        $search = ['class'];

        return ucfirst(trim(str_replace($search, $replace, strtolower(preg_replace(['/([A-Z])/', '/[_\s]+/'], ['_$1', ' '], $text)))));
    }

    private function add(Message $message, MessageCatalogue $catalogue, ?MessageCatalogue $currentCatalogue): void
    {
        if (!empty($currentCatalogue) && $currentCatalogue->has($message)) {
            return;
        }

        $catalogue->add($message);
    }
}
