services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EzSystems\EzPlatformAdminUi\UI\Module\ContentTree\NodeFactory:
        arguments:
            $displayLimit: '$content_tree_module.load_more_limit$'
            $childrenLoadMaxLimit: '$content_tree_module.children_load_max_limit$'
            $maxDepth: '$content_tree_module.tree_max_depth$'
            $allowedContentTypes: '$content_tree_module.allowed_content_types$'
            $ignoredContentTypes: '$content_tree_module.ignored_content_types$'

    EzSystems\EzPlatformAdminUi\UI\Config\Provider\Module\ContentTree:
        tags:
            - { name: ezplatform.admin_ui.config_provider, key: 'contentTree' }
