services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  EzSystems\EzPlatformAdminUi\UI\Module\FieldTypeToolbar\FieldTypeToolbarFactory:
    arguments:
        - '@eZ\Publish\Core\FieldType\FieldTypeRegistry'
        - '@translator'
