active_domains:
    - 'admin_ui_admin_limitation_pick'
    - 'admin_ui_admin_trash_list'
    - 'admin_ui_cotf_create'
    - 'admin_ui_field_type_ezobjectrelationlist'
    - 'admin_ui_udw_browse'
    - 'admin_ui_udw_copy'
    - 'admin_ui_udw_copy_subtree'
    - 'admin_ui_udw_locations_tab'
    - 'admin_ui_udw_move'
    - 'admin_ui_udw_swap'
