active_domains:
    - 'admin_ui_frontend_admin_limitation_pick'
    - 'admin_ui_frontend_admin_location_load_map'
    - 'admin_ui_frontend_admin_trash_list'
    - 'admin_ui_frontend_cotf_create'
    - 'admin_ui_frontend_field_type_ezobjectrelationlist'
    - 'admin_ui_frontend_udw_browse'
    - 'admin_ui_frontend_udw_copy'
    - 'admin_ui_frontend_udw_copy_subtree'
    - 'admin_ui_frontend_udw_locations_tab'
    - 'admin_ui_frontend_udw_move'
    - 'admin_ui_frontend_udw_swap'
