active_domains:
    - 'universal_discovery_widget'
    - 'alloy_editor'
    - 'fieldtypes_edit'
    - 'notifications'
    - 'search'
    - 'content'
    - 'multi_file_upload'
    - 'sub_items'
    - 'content_tree'
