#
# System routes
#

_ezpublishLocation:
    path: /content/location/{locationId}/{languageCode}/{viewType}/{layout}
    options:
        expose: true
    defaults:
        _controller: ez_content:viewLocation
        viewType: full
        layout: true
        languageCode: null

#
# Dashboard
#

ezplatform.dashboard:
    path: /dashboard
    defaults:
        _controller: 'FrameworkBundle:Template:template'
        template: 'EzPlatformAdminUiBundle:dashboard:dashboard.html.twig'

#
# System Information
#

ezplatform.systeminfo:
    path: /systeminfo
    defaults:
        _controller: 'EzPlatformAdminUiBundle:SystemInfo:info'

ezplatform.systeminfo.php:
    path: /systeminfo/phpinfo
    defaults:
        _controller: 'EzPlatformAdminUiBundle:SystemInfo:phpinfo'

#
# Section
#

ezplatform.section.list:
    path: /section/list
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Section:list'

ezplatform.section.create:
    path: /section/create
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Section:create'

ezplatform.section.view:
    path: /section/view/{sectionId}
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Section:view'

ezplatform.section.update:
    path: /section/update/{sectionId}
    defaults:
        sectionId: null
        _controller: 'EzPlatformAdminUiBundle:Section:update'

ezplatform.section.delete:
    path: /section/delete/{sectionId}
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Section:delete'

ezplatform.section.bulk_delete:
    path: /section/bulk-delete
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Section:bulkDelete'

ezplatform.section.assign_content:
    path: /section/assign-content/{sectionId}
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Section:assignContent'

#
# Language
#

ezplatform.language.list:
    path: /language/list
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Language:list'

ezplatform.language.view:
    path: /language/view/{languageId}
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Language:view'

ezplatform.language.create:
    path: /language/create
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Language:create'

ezplatform.language.edit:
    path: /language/edit/{languageId}
    defaults:
        languageId: null
        _controller: 'EzPlatformAdminUiBundle:Language:edit'

ezplatform.language.delete:
    path: /language/delete/{languageId}
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Language:delete'

ezplatform.language.bulk_delete:
    path: /language/bulk-delete
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Language:bulkDelete'

#
# Role
#

ezplatform.role.list:
    path: /role/list
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Role:list'

ezplatform.role.view:
    path: /role/{roleId}
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Role:view'
    requirements:
        roleId: \d+

ezplatform.role.create:
    path: /role/create
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Role:create'

ezplatform.role.update:
    path: /role/{roleId}/update
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Role:update'
    requirements:
        roleId: \d+

ezplatform.role.delete:
    path: /role/{roleId}/delete
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Role:delete'
    requirements:
        roleId: \d+

ezplatform.role.bulk_delete:
    path: /role/bulk-delete
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Role:bulkDelete'

#
# Policy
#

ezplatform.policy.list:
    path: /role/{roleId}/policy/list
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Policy:list'
    requirements:
        roleId: \d+

ezplatform.policy.create:
    path: /role/{roleId}/policy/create
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Policy:create'
    requirements:
        roleId: \d+

ezplatform.policy.update:
    path: /role/{roleId}/policy/{policyId}/update
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Policy:update'
    requirements:
        roleId: \d+
        policyId: \d+

ezplatform.policy.delete:
    path: /role/{roleId}/policy/{policyId}
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Policy:delete'
    requirements:
        roleId: \d+
        policyId: \d+

ezplatform.policy.bulk_delete:
    path: /role/{roleId}/policy/bulk-delete
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Policy:bulkDelete'
    requirements:
        roleId: \d+

#
# Role Assignment
#

ezplatform.role_assignment.list:
    path: /role/{roleId}/assignment
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:RoleAssignment:list'

ezplatform.role_assignment.create:
    path: /role/{roleId}/assignment/create
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:RoleAssignment:create'
    requirements:
        roleId: \d+

ezplatform.role_assignment.delete:
    path: /role/{roleId}/assignment/{assignmentId}/delete
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:RoleAssignment:delete'

ezplatform.role_assignment.bulk_delete:
    path: /role/{roleId}/assignment/bulk-delete
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:RoleAssignment:bulkDelete'
    requirements:
        roleId: \d+

#
# Content Type Group
#

ezplatform.content_type_group.list:
    path: /contenttypegroup/list
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentTypeGroup:list'

ezplatform.content_type_group.view:
    path: /contenttypegroup/{contentTypeGroupId}/{page}
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentTypeGroup:view'
        page: 1
    requirements:
        contentTypeGroupId: \d+
        page: \d+

ezplatform.content_type_group.create:
    path: /contenttypegroup/create
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentTypeGroup:create'

ezplatform.content_type_group.update:
    path: /contenttypegroup/{contentTypeGroupId}/update
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentTypeGroup:update'
    requirements:
        contentTypeGroupId: \d+

ezplatform.content_type_group.delete:
    path: /contenttypegroup/{contentTypeGroupId}/delete
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentTypeGroup:delete'
    requirements:
        contentTypeGroupId: \d+

ezplatform.content_type_group.bulk_delete:
    path: /contenttypegroup/bulk-delete
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentTypeGroup:bulkDelete'

#
# Trash
#

ezplatform.trash.list:
    path: /trash/list
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Trash:list'

ezplatform.trash.empty:
    path: /trash/empty
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Trash:empty'

ezplatform.trash.restore:
    path: /trash/restore
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Trash:restore'

#
# Content Type
#

ezplatform.content_type.list:
    path: /contenttypegroup/{contentTypeGroupId}/contenttype/list
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentType:list'
    requirements:
        contentTypeGroupId: \d+

ezplatform.content_type.add:
    path: /contenttypegroup/{contentTypeGroupId}/contenttype/add
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentType:add'
    requirements:
        contentTypeGroupId: \d+

ezplatform.content_type.edit:
    path: /contenttypegroup/{contentTypeGroupId}/contenttype/{contentTypeId}/edit
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentType:edit'
    requirements:
        contentTypeGroupId: \d+

ezplatform.content_type.update:
    path: /contenttypegroup/{contentTypeGroupId}/contenttype/{contentTypeId}/update
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentType:update'
    requirements:
        contentTypeGroupId: \d+

ezplatform.content_type.delete:
    path: /contenttypegroup/{contentTypeGroupId}/contenttype/{contentTypeId}
    methods: ['DELETE']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentType:delete'
    requirements:
        contentTypeGroupId: \d+

ezplatform.content_type.bulk_delete:
    path: /content_type/{contentTypeGroupId}/bulk-delete
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentType:bulkDelete'
    requirements:
        contentTypeGroupId: \d+

ezplatform.content_type.view:
    path: /contenttypegroup/{contentTypeGroupId}/contenttype/{contentTypeId}
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentType:view'
    requirements:
        contentTypeGroupId: \d+

#
# Location View
#

ezplatform.location.move:
    path: /location/move
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Location:move'

ezplatform.location.copy:
    path: /location/copy
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Location:copy'

ezplatform.location.trash:
    path: /location/trash
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Location:trash'

ezplatform.location.update:
    path: /location/update
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Location:update'

# LocationView / Translation tab

ezplatform.translation.add:
    path: /translation/add
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Translation:add'

ezplatform.translation.remove:
    path: /translation/remove
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Translation:remove'

# LocationView / Versions tab

ezplatform.version.remove:
    path: /version/remove
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Version:remove'

# LocationView / Locations tab

ezplatform.location.add:
    path: /location/add
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Location:add'

ezplatform.location.remove:
    path: /location/remove
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Location:remove'

ezplatform.location.swap:
    path: /location/swap
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Location:swap'

ezplatform.location.update_visibility:
    path: /location/update-visibility
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Location:updateVisibility'

ezplatform.content.update_main_location:
    path: /content/update-main-location
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Content:updateMainLocation'

#
# Content Edit
#

ezplatform.content.edit:
    path: /content/edit
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Content:edit'

ezplatform.content.create:
    path: /content/create
    methods: ['POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Content:create'

ezplatform.content.preview:
    path: /content/{contentId}/preview/{versionNo}/{languageCode}
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Content:preview'
        languageCode: ~

ezplatform.content.translate:
    path: /content/{contentId}/translate/{toLanguageCode}/{fromLanguageCode}
    methods: ['GET', 'POST']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:ContentEdit:translate'
        fromLanguageCode: ~

#
# Search
#

ezplatform.search:
    path: /search
    methods: ['GET']
    defaults:
        _controller: 'EzPlatformAdminUiBundle:Search:search'

#
# Link manager
#

ezplatform.link_manager.list:
    path: /linkmanagement
    defaults:
        _controller: 'EzPlatformAdminUiBundle:LinkManager:list'

ezplatform.link_manager.edit:
    path: /linkmanagement/edit/{urlId}
    defaults:
        _controller: 'EzPlatformAdminUiBundle:LinkManager:edit'
    requirements:
        urlId: \d+

ezplatform.link_manager.view:
    path: /linkmanagement/view/{urlId}
    defaults:
        _controller: 'EzPlatformAdminUiBundle:LinkManager:view'
    requirements:
        urlId: \d+
