name: PR check
on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  test-base-branch:
    uses: ezsystems/ezplatform-admin-ui/.github/workflows/test.yaml@ci-pr-verification-reusable
