name: Pull Request base branch verification
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  test-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Download composer.json from Pull Request
        env:
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
        run: |
          curl --url $GITHUB_API_URL/repos/$HEAD_REPO/contents/composer.json?ref=$GITHUB_HEAD_REF \
          --header 'Accept: application/vnd.github.v3.raw' \
          > pr_composer.json;
      - name: Set branch-alias from Pull Request
        run: |
          CURRENT_BRANCH_ALIAS=$(cat pr_composer.json | jq -r '.["extra"]["branch-alias"] | flatten | .[0]')
          echo "CURRENT_BRANCH_ALIAS=${CURRENT_BRANCH_ALIAS}" >> $GITHUB_ENV
          echo $CURRENT_BRANCH_ALIAS
      - name: Download composer.json from base branch
        run: |
          curl --url $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/contents/composer.json?ref=$GITHUB_BASE_REF \
          --header 'Accept: application/vnd.github.v3.raw' \
          > base_composer.json;  
      - name: Get base branch-alias
        run: |
          BASE_BRANCH_ALIAS=$(cat base_composer.json | jq -r '.["extra"]["branch-alias"] | flatten | .[0]')
          echo "BASE_BRANCH_ALIAS=${BASE_BRANCH_ALIAS}" >> $GITHUB_ENV
      - name: Check if base branch is correct
        run: if [ "$CURRENT_BRANCH_ALIAS" != "$BASE_BRANCH_ALIAS" ]; then exit 1; fi
