services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EzSystems\EzPlatformAdminUi\Behat\BusinessContext\NavigationContext:
        arguments:
            $argumentParser: '@EzSystems\Behat\Core\Behat\ArgumentParser'

    EzSystems\EzPlatformAdminUi\Behat\BusinessContext\ContentViewContext:
        arguments:
            $argumentParser: '@EzSystems\Behat\Core\Behat\ArgumentParser'

    EzSystems\EzPlatformAdminUi\Behat\BusinessContext\UDWContext:
        arguments:
            $argumentParser: '@EzSystems\Behat\Core\Behat\ArgumentParser'
