services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    EzSystems\EzPlatformAdminUi\Form\Type\:
        resource: '../../../lib/Form/Type'

    EzSystems\EzPlatformAdminUi\Form\Type\Language\LimitedLanguageChoiceType:
        arguments:
            $siteaccessLanguages: '$languages$'
