services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\UI\Action\EventDispatcher: ~
    EzSystems\EzPlatformAdminUi\UI\Action\EventDispatcherInterface: '@EzSystems\EzPlatformAdminUi\UI\Action\EventDispatcher'

    EzSystems\EzPlatformAdminUi\UI\Action\FormUiActionMapper:
        tags:
            - { name: ezplatform.admin_ui.form_ui_action_mapper }

    EzSystems\EzPlatformAdminUi\UI\Action\FormUiActionMapperInterface:
        alias: '@EzSystems\EzPlatformAdminUi\UI\Action\FormUiActionMapper'

    EzSystems\EzPlatformAdminUi\UI\Action\FormUiActionMappingDispatcher:
        arguments:
            $mappers: !tagged ezplatform.admin_ui.form_ui_action_mapper
            $defaultMapper: '@EzSystems\EzPlatformAdminUi\UI\Action\FormUiActionMapper'
