parameters:
    ezplatform.content_forms.form_processor.content_type.options.redirect_route_after_publish: ~
    ezplatform.content_forms.form_processor.content_type.options:
        redirectRouteAfterPublish: "%ezplatform.content_forms.form_processor.content_type.options.redirect_route_after_publish%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformAdminUi\Form\Processor\Content\AutosaveProcessor: ~

    EzSystems\EzPlatformAdminUi\Form\Processor\Content\ContentOnTheFlyProcessor:
        arguments:
            $innerContentFormProcessor: '@ezplatform.content_forms.form_processor.content'

    EzSystems\EzPlatformAdminUi\Form\Processor\Content\UrlRedirectProcessor:
        public: true
        decorates: EzSystems\EzPlatformContentForms\Form\Processor\SystemUrlRedirectProcessor
        arguments:
            $siteaccessGroups: '%ezpublish.siteaccess.groups%'
            $systemUrlRedirectProcessor: '@EzSystems\EzPlatformAdminUi\Form\Processor\Content\UrlRedirectProcessor.inner'

    EzSystems\EzPlatformAdminUi\Form\Processor\ContentEditNotificationFormProcessor:
        public: true
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'

    EzSystems\EzPlatformAdminUi\Form\Processor\ContentType\ContentTypeDiscardChangesFormProcessor: ~

    EzSystems\EzPlatformAdminUi\Form\Processor\ContentType\ContentTypeFormProcessor:
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@router"
            - "%ezplatform.content_forms.form_processor.content_type.options%"
        calls:
            - [ setGroupsList, [ "@ezpublish.fields_groups.list" ] ]

    EzSystems\EzPlatformAdminUi\Form\Processor\PreviewFormProcessor: ~

    EzSystems\EzPlatformAdminUi\Form\Processor\TranslationFormProcessor: ~

    EzSystems\EzPlatformAdminUi\Form\Processor\User\UserOnTheFlyProcessor:
        arguments:
            $innerUserUpdateFormProcessor: '@ezplatform.content_forms.form_processor.user_update'
