services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # Menu Item Factory
    #

    EzSystems\EzPlatformAdminUi\Menu\MenuItemFactory: ~

    #
    # Menu Builders
    #

    EzSystems\EzPlatformAdminUi\Menu\MainMenuBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.main }

    EzSystems\EzPlatformAdminUi\Menu\UserMenuBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.user }

    EzSystems\EzPlatformAdminUi\Menu\LeftSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content.sidebar_left }

    EzSystems\EzPlatformAdminUi\Menu\ContentRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\TrashRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.trash.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\ContentEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content_edit.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\ContentCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content_create.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\SectionEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.section_edit.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\SectionCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.section_create.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\Role\PolicyEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.policy_edit.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\Role\PolicyCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.policy_create.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\Role\RoleEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.role_edit.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\Role\RoleCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.role_create.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\UserCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.user_create.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\UserEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.user_edit.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\Role\RoleAssignmentCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.role_assignment_create.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\Language\LanguageCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.language_create.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\Language\LanguageEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.language_edit.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\ContentType\ContentTypeGroupCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content_type_group_create.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\ContentType\ContentTypeGroupEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content_type_group_edit.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\ContentType\ContentTypeCreateRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content_type_create.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\Admin\ContentType\ContentTypeEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.content_type_edit.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\URLEditRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.url_edit.sidebar_right }

    EzSystems\EzPlatformAdminUi\Menu\UserPasswordChangeRightSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: ezplatform_admin_ui.menu.user_password_change.sidebar_right }
