services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\Permission\PermissionChecker: ~

    EzSystems\EzPlatformAdminUi\Permission\PermissionCheckerInterface:
        alias: EzSystems\EzPlatformAdminUi\Permission\PermissionChecker

    EzSystems\EzPlatformAdminUi\Permission\LookupLimitationsTransformer: ~
