services:
  EzSystems\EzPlatformAdminUi\Search\AbstractPagerContentToDataMapper:
    abstract: true
    autowire: true
    public: false
    arguments:
      $translationHelper: '@ezpublish.translation_helper'

  EzSystems\EzPlatformAdminUi\Search\PagerSearchContentToDataMapper:
    parent: Ibexa\Platform\Search\Mapper\PagerSearchContentToDataMapper
    autowire: true
    public: false
