services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Repository Forms
    EzSystems\EzPlatformAdminUi\Form\Type\Role\LimitationType: '@ezplatform.content_forms.policy.limitation.form'

    # Symfony
    Symfony\Contracts\Translation\TranslatorInterface: '@translator'
