services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\Siteaccess\SiteaccessResolverInterface: '@EzSystems\EzPlatformAdminUi\Siteaccess\SiteaccessResolver'

    EzSystems\EzPlatformAdminUi\Siteaccess\SiteAccessKeyGenerator: ~

    EzSystems\EzPlatformAdminUi\Siteaccess\SiteAccessNameGenerator: ~

    EzSystems\EzPlatformAdminUi\Siteaccess\SiteaccessResolver:
        arguments:
            $siteaccessPreviewVoters: !tagged ezplatform.admin_ui.siteaccess_preview_voter
            $siteAccessService: '@ezpublish.siteaccess_service'

    EzSystems\EzPlatformAdminUi\Siteaccess\NonAdminSiteaccessResolver:
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'

    EzSystems\EzPlatformAdminUi\Siteaccess\AdminSiteaccessPreviewVoter:
        tags: ['ezplatform.admin_ui.siteaccess_preview_voter']
