services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\Translation\Extractor\JavaScriptFileVisitor:
        tags:
            - { name: jms_translation.file_visitor }

    EzSystems\EzPlatformAdminUi\Translation\Extractor\PolicyTranslationExtractor:
        arguments:
            - '%ezpublish.api.role.policy_map%'
        tags:
            - { name: jms_translation.extractor, alias: ez_policy }

    EzSystems\EzPlatformAdminUi\Translation\Extractor\NotificationTranslationExtractor:
        tags:
            - { name: jms_translation.file_visitor }
