services:
    EzSystems\EzPlatformUser\ExceptionHandler\ActionResultHandler: '@EzSystems\EzPlatformAdminUi\Notification\TranslatableNotificationHandler'
    EzSystems\EzPlatformUser\Form\SubmitHandler: '@EzSystems\EzPlatformAdminUi\Form\SubmitHandler'
