services:
    #
    # User Settings Implementations
    #
    EzSystems\EzPlatformAdminUi\UserSetting\Setting\Timezone:
        parent: EzSystems\EzPlatformUser\UserSetting\Setting\Timezone

    EzSystems\EzPlatformAdminUi\UserSetting\Setting\SubitemsLimit:
        parent: EzSystems\EzPlatformUser\UserSetting\Setting\SubitemsLimit

    #
    # UpdateFormType
    #
    EzSystems\EzPlatformAdminUi\Form\Type\User\Setting\UserSettingUpdateType:
        parent: EzSystems\EzPlatformUser\Form\Type\UserSettingUpdateType

    EzSystems\EzPlatformAdminUi\UserSetting\Setting\Language:
        autowire: true
        autoconfigure: true
        public: false
        arguments:
            $availableLocaleChoiceLoader: '@EzSystems\EzPlatformAdminUi\Form\Type\ChoiceList\Loader\AvailableLocaleChoiceLoader'
        tags:
            - { name: ezplatform.admin_ui.user_setting.value, identifier: language }
            - { name: ezplatform.admin_ui.user_setting.form_mapper, identifier: language }
