services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\UserSetting\UserSettingService: ~
    EzSystems\EzPlatformAdminUi\UserSetting\ValueDefinitionRegistry: ~
    EzSystems\EzPlatformAdminUi\UserSetting\FormMapperRegistry: ~

    #
    # User Settings Implementations
    #
    EzSystems\EzPlatformAdminUi\UserSetting\Setting\Timezone:
        tags:
            - { name: ezplatform.admin_ui.user_setting.value, identifier: timezone }
            - { name: ezplatform.admin_ui.user_setting.form_mapper, identifier: timezone }

    EzSystems\EzPlatformAdminUi\UserSetting\Setting\SubitemsLimit:
        arguments:
            $subitemsLimit: '$subitems_module.limit$'
        tags:
            - { name: ezplatform.admin_ui.user_setting.value, identifier: subitems_limit }
            - { name: ezplatform.admin_ui.user_setting.form_mapper, identifier: subitems_limit }

    EzSystems\EzPlatformAdminUi\UserSetting\Setting\CharactersCounter:
        tags:
            - { name: ezplatform.admin_ui.user_setting.value, identifier: characters_counter }
            - { name: ezplatform.admin_ui.user_setting.form_mapper, identifier: characters_counter }
