services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\Util\:
        resource: "../../../lib/Util"

    EzSystems\EzPlatformAdminUi\Util\PermissionUtilInterface:
        alias: EzSystems\EzPlatformAdminUi\Util\PermissionUtil
